# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0003_auto_20180206_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='fitb_ans',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
