# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-06 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0004_auto_20180206_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_no',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
