# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import quizapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0005_auto_20180207_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to=quizapi.models.user_directory_path),
        ),
    ]
