# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapi', '0008_auto_20180215_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='img',
        ),
    ]
